Vagrant.configure(2) do |config|

  # config.vm.box = "ubuntu/trusty64"
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
	vb.name = "_ots"
	vb.memory = 512
	vb.cpus = 1
  end

  config.vm.network "forwarded_port", guest: 7143, host: 7143, host_ip: "127.0.0.1", auto_correct: true

  config.vm.provision "shell", inline: <<-SHELL
    # Allow password auth in ubuntu/xenial64 [avoids "Disconnected: No supported authentication methods available (server sent: publickey)"]
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config && systemctl reload sshd
    rm /etc/localtime && ln -s /usr/share/zoneinfo/Europe/London /etc/localtime
    apt-get update
    apt-get install -y tree git nano puppet
    puppet module install puppetlabs-stdlib --version 4.25.1
  SHELL

  config.vm.provision "puppet" do |puppet|
    puppet.module_path="../../"
    puppet.hiera_config_path = "hiera.yaml"
    puppet.facter = {
      "vagrant" => "1"
    }
  end

end
